name: CD
on:
  push:
    tags:
      - "V*.*.*"

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
        with:
          install: true
          cache: true
          experimental: true

      - name: Extract version number
        id: extract_version
        run: echo "version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/V\(.*\)/\1/')" >> $GITHUB_ENV

      - name: Restore dependencies
        run: mise run restore

      - name: Build
        run: mise run build Release -p:Version=${{ env.version }}

      - name: Test
        run: mise run test ./tmp

      - name: Publish
        env:
          SECRETS_NUGETORG_API: ${{ secrets.NUGETORG_API }}
        run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key "$SECRETS_NUGETORG_API" --source https://api.nuget.org/v3/index.json
