name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
        with:
          install: true
          cache: true
          experimental: true

      - name: Run dotnet format
        run: mise run check-format

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
        with:
          install: true
          cache: true
          experimental: true

      - name: Restore dependencies
        run: mise run restore

      - name: Build
        run: mise run build --config Release

      - name: Test
        run: mise run tests --output ./tmp

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
